import { describe, expect, it } from 'vitest';
import { surrogateKey } from './surrogate-key';

describe('surrogateKey', () => {
  it('pins a fixed input to the value the current implementation produces', () => {
    // Generated by running surrogateKey('sp_guppy', 20260829) against today's
    // implementation. If a "tidy up" of the prime, mask, or shift ever
    // changes this, every warehouse key silently changes with it, so this
    // hardcoded value is the tripwire.
    expect(surrogateKey('sp_guppy', 20260829).toString()).toBe('4599680394370243580');
  });

  it('stays non-negative and inside signed 64-bit range', () => {
    // The `>> 1n` exists so every destination (including columns typed as
    // signed BIGINT) can store the result. Losing that shift would still
    // pass the fixed-value test above for some inputs, so assert the range
    // property directly.
    const maxSigned64 = 2n ** 63n - 1n;
    const key = surrogateKey('sp_pterophyllum_scalare', 20260829);
    expect(key >= 0n).toBe(true);
    expect(key <= maxSigned64).toBe(true);
  });

  it('gives the same key for the same input every time', () => {
    expect(surrogateKey('sp_betta', 1)).toBe(surrogateKey('sp_betta', 1));
  });

  it('treats differently-shaped parts as distinct, mostly', () => {
    // Multi-part keys are distinct from an unrelated single string.
    expect(surrogateKey('a', 'b')).not.toBe(surrogateKey('ab'));

    // But the join delimiter is '|' and it is not escaped, so a part that
    // happens to contain a literal '|' collides with the multi-part call
    // that would produce the same joined string. This is real, current
    // behaviour, not a bug this test is asserting away.
    expect(surrogateKey('a', 'b')).toBe(surrogateKey('a|b'));
  });
});
