/**
 * Which deployment this build is, and the two things that follow from it.
 *
 * One module rather than two, because the local database name and the cloud
 * database URL must never disagree about which environment they are in. A
 * build holding production's IndexedDB and staging's cloud database would be
 * the worst kind of bug: silently wrong, and only visible once someone's fish
 * arrive in the wrong place.
 *
 * Everything here is derived from the Vite `base` path, which is already how
 * this repo distinguishes its environments (see vite.config.ts).
 */

export type Deployment = 'production' | 'staging' | 'other';

/** Where this build is deployed, judged by the base path baked in at build time. */
export function deploymentFor(base: string): Deployment {
  if (base.endsWith('/uat/')) return 'staging';
  if (base === '/Fish2tank/') return 'production';
  return 'other';
}

// --- The local database (BUG-04) -------------------------------------------

/** The production database name. Never change this without a migration. */
export const PRODUCTION_DB_NAME = 'fish2tank';

/**
 * Which IndexedDB database a build should open (BUG-04).
 *
 * IndexedDB is scoped per ORIGIN, not per path. Both environments deploy to
 * `leonidas47dario.github.io` - production at `/Fish2tank/` and staging at
 * `/Fish2tank/uat/` - so until this existed they shared one database called
 * `fish2tank`. A UAT build with a schema bug could corrupt production records,
 * which is the exact thing the UAT gate (FR-R14) exists to prevent.
 *
 * PRODUCTION KEEPS THE NAME `fish2tank`. That is not an aesthetic choice. The
 * real collection lives in a database with that name today, and renaming it
 * would present an empty app to the person whose fish they are. Only staging
 * moves, and staging opening empty once is the intended, one-time cost.
 *
 * `other` gets the production name deliberately. Only the deployed pair share
 * an origin, so a dev server on localhost or a preview on some other host
 * cannot collide with them, and giving it a different name would only make
 * local work diverge from what ships.
 */
export function databaseNameFor(base: string): string {
  return deploymentFor(base) === 'staging'
    ? `${PRODUCTION_DB_NAME}-uat`
    : PRODUCTION_DB_NAME;
}

// --- The cloud database (spec 005) -----------------------------------------

/**
 * The Dexie Cloud database per deployment. Not secret: the URL ships in the
 * client bundle by design, and every one of these is origin-whitelisted and
 * refuses unknown callers. The secrets live in Dexie Cloud Manager.
 */
export const CLOUD_DATABASES = {
  production: 'https://zecprrllc.dexie.cloud',
  staging: 'https://zblsiza99.dexie.cloud',
  /** Throwaway. Anything that is not a recognised deployment lands here. */
  other: 'https://z84eopr5r.dexie.cloud',
} as const satisfies Record<Deployment, string>;

/**
 * Which cloud database to sync with.
 *
 * NOTE THE ASYMMETRY WITH `databaseNameFor`, which is deliberate. An
 * unrecognised build gets production's *local* name, because local databases
 * only collide within an origin and there is nothing to collide with. It gets
 * the *scratch* cloud database, because a cloud database is global: a dev
 * server, a preview deploy or a half-configured host reaching production and
 * writing to Ryan's real realm is a genuine way to lose data. Unrecognised
 * therefore means throwaway, never production.
 */
export function cloudDatabaseUrlFor(base: string): string {
  return CLOUD_DATABASES[deploymentFor(base)];
}

/**
 * FR-A01's data boundary: what never leaves the device.
 *
 * `species` and `speciesProfiles` are seeded from `marts/*.json`, which ships
 * inside the bundle and is regenerated by `npm run marts`. Syncing them would
 * spend megabytes of a 25 MB object-storage budget replicating bytes already
 * present on every device, and would let a stale device push an outdated
 * catalog over a fresh one.
 *
 * `blobs` is the megabytes, and they go to R2 (FR-A03). `draftKeys` exists to
 * deduplicate retries on one device (FR-C07); synced, one device's abandoned
 * draft would resurface on another. `deletedRecords` is local tombstone
 * bookkeeping against this device's own seeders.
 *
 * Verified empirically on 2026-08-30: none of these appear in a server-side
 * export after a full sync. See spec 005 FR-A06.
 */
export const UNSYNCED_TABLES = [
  'blobs',
  'draftKeys',
  'species',
  'speciesProfiles',
  'deletedRecords',
] as const;
